//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManyWords.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManyWords.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddVocabulary_AddButton
        {
            get
            {
                return ResourceManager.GetString("AddVocabulary_AddButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter name for new vocabulary:.
        /// </summary>
        public static string AddVocabulary_Hint
        {
            get
            {
                return ResourceManager.GetString("AddVocabulary_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap somewhere to continue.
        /// </summary>
        public static string AnswerChoice_ContinueHint
        {
            get
            {
                return ResourceManager.GetString("AnswerChoice_ContinueHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap on a correct answer from above.
        /// </summary>
        public static string AnswerChoice_TapHint
        {
            get
            {
                return ResourceManager.GetString("AnswerChoice_TapHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ManyWords.
        /// </summary>
        public static string AppName
        {
            get
            {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string LanguageSelect_ButtonSelect
        {
            get
            {
                return ResourceManager.GetString("LanguageSelect_ButtonSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to new word.
        /// </summary>
        public static string MainPage_ButtonNewWord
        {
            get
            {
                return ResourceManager.GetString("MainPage_ButtonNewWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to training.
        /// </summary>
        public static string MainPage_ButtonTraining
        {
            get
            {
                return ResourceManager.GetString("MainPage_ButtonTraining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string MainPage_PanoramaTitleStart
        {
            get
            {
                return ResourceManager.GetString("MainPage_PanoramaTitleStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vocabs.
        /// </summary>
        public static string MainPage_PanoramaTitleVocabularies
        {
            get
            {
                return ResourceManager.GetString("MainPage_PanoramaTitleVocabularies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select language you learn.
        /// </summary>
        public static string MainPage_SelectLanguageTip
        {
            get
            {
                return ResourceManager.GetString("MainPage_SelectLanguageTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a new word, you can either skip or start learning it.
        /// </summary>
        public static string PresentWord_Hint
        {
            get
            {
                return ResourceManager.GetString("PresentWord_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string PresentWord_Learn
        {
            get
            {
                return ResourceManager.GetString("PresentWord_Learn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string PresentWord_Skip
        {
            get
            {
                return ResourceManager.GetString("PresentWord_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string SpellingCheck_ButtonCheck
        {
            get
            {
                return ResourceManager.GetString("SpellingCheck_ButtonCheck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap somewhere to continue.
        /// </summary>
        public static string SpellingCheck_ContinueHint
        {
            get
            {
                return ResourceManager.GetString("SpellingCheck_ContinueHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter translation for the word above.
        /// </summary>
        public static string SpellingCheck_Hint
        {
            get
            {
                return ResourceManager.GetString("SpellingCheck_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading words....
        /// </summary>
        public static string TrainingView_Progress
        {
            get
            {
                return ResourceManager.GetString("TrainingView_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WordEditor_ButtonOK
        {
            get
            {
                return ResourceManager.GetString("WordEditor_ButtonOK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to new word.
        /// </summary>
        public static string WordEditor_TitleAdd
        {
            get
            {
                return ResourceManager.GetString("WordEditor_TitleAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to edit word.
        /// </summary>
        public static string WordEditor_TitleEdit
        {
            get
            {
                return ResourceManager.GetString("WordEditor_TitleEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string WordEditor_TranslationTitle
        {
            get
            {
                return ResourceManager.GetString("WordEditor_TranslationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vocabulary.
        /// </summary>
        public static string WordEditor_VocabularyPickerTitle
        {
            get
            {
                return ResourceManager.GetString("WordEditor_VocabularyPickerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string WordsView_All
        {
            get
            {
                return ResourceManager.GetString("WordsView_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string WordsView_Delete
        {
            get
            {
                return ResourceManager.GetString("WordsView_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string WordsView_Done
        {
            get
            {
                return ResourceManager.GetString("WordsView_Done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string WordsView_Edit
        {
            get
            {
                return ResourceManager.GetString("WordsView_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to learning.
        /// </summary>
        public static string WordsView_Learning
        {
            get
            {
                return ResourceManager.GetString("WordsView_Learning", resourceCulture);
            }
        }
    }
}
