//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManyWords.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManyWords.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManyWords.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new word.
        /// </summary>
        public static string MainPage_ButtonNewWord {
            get {
                return ResourceManager.GetString("MainPage_ButtonNewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to training.
        /// </summary>
        public static string MainPage_ButtonTraining {
            get {
                return ResourceManager.GetString("MainPage_ButtonTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string MainPage_PanoramaTitleStart {
            get {
                return ResourceManager.GetString("MainPage_PanoramaTitleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vocabs.
        /// </summary>
        public static string MainPage_PanoramaTitleVocabularies {
            get {
                return ResourceManager.GetString("MainPage_PanoramaTitleVocabularies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language you learn.
        /// </summary>
        public static string MainPage_SelectLanguageTip {
            get {
                return ResourceManager.GetString("MainPage_SelectLanguageTip", resourceCulture);
            }
        }
    }
}
